### ISSUE TITLE
Photoshop doesn't load

### ISSUE THREAD

**Issue by thespyboss** [YoungFellow-le/Linux-PhotoshopCC-v22#1]
I tried installing today which went perfectly fine. When I try to start the app up from my menu, it doesn't load, and if I run the command from my terminal, the photo shows what it returns before crashing.
![image](https://user-images.githubusercontent.com/42257053/165988880-312c5847-30a2-4bd5-8d1a-c9e5156e474d.png)

**Comment by YoungFellow-le** [comment]
Hi @thespyboss, I'm sorry your facing this problem.]
Have you tried using `wine` rather than `wine64`?

**Comment by YoungFellow-le** [comment]
If that doesn't help, then please post the output of:
```
ls /home/`whoami`/Linux-PhotoshopCC-v22/PS-Prefix/drive_c/Program Files/Adobe/Adobe Photoshop 2021/ | grep 'photoshop'
```

**Comment by thespyboss** [comment]
> Hi @thespyboss, I'm sorry your facing this problem.] Have you tried using `wine` rather than `wine64`?

I just did which got me this 
![image](https://user-images.githubusercontent.com/42257053/166148573-5f33e6e5-473a-4d3d-9289-a4a9a58d503b.png)



> If that doesn't help, then please post the output of:
> 
> ```
> ls "/home/`whoami`/Linux-PhotoshopCC-v22/PS-Prefix/drive_c/Program Files/Adobe/Adobe Photoshop 2021/" | grep 'photoshop'
> ```
Running the code you said above to run got me 
![image](https://user-images.githubusercontent.com/42257053/166148673-4feda20d-a60f-4da3-b56a-f08ff698218e.png)

**Comment by thespyboss** [comment]
I think the tar.xz file that is the AdobePhotoshop installer, isn't downloading from the hosting site you have set. It appears in my computer as a .txt file once everything is done. Also while it is installing, this is what I get while installing all of the files before the installation
![image](https://user-images.githubusercontent.com/42257053/166148924-d73f3ff6-1fa8-42e4-b3ba-7d77b635b17f.png)
I would want to bet that it isn't running because photoshop isn't actually installing. That's why above, it can't find the Adobe Photoshop 2021 folder.

**Comment by YoungFellow-le** [comment]
I used to get that problem too sometimes, and it has to do with you internet provider.
I ran a test run today and it worked fine, so it's a network related problem.

**Comment by YoungFellow-le** [comment]
I'm going to change the server host soon, but I'll move the repo first to an independent one first. So maybe that will solve the issue.
