### ISSUE TITLE
Desktop entry isn't showing up

### ISSUE THREAD

**Issue by DaanKorver** [YoungFellow-le/Linux-PhotoshopCC-v22#3]
I tried to manually make a desktop entry just like the installer said but for some reason it just won't show up.

```
[Desktop Entry]
Name=Photoshop CC
Exec=cd "/home/daan/Downloads/Linux-PhotoshopCC-v22/PS-Prefix/drive_c/Program Files/Adobe/Adobe Photoshop 2021/" && WINEPREFIX="/home/daan/Downloads/Linux-PhotoshopCC-v22/PS-Prefix" wine photoshop.exe
Type=Application
Comment=Photoshop CC 2021
Categories=Graphics;2DGraphics;RasterGraphics;GTK;
Icon=/home/daan/Downloads/Linux-PhotoshopCC-v22/.photoshop.png
StartupWMClass=photoshop.exe
MimeType=image/png;image/psd;image;
```

**Comment by YoungFellow-le** [comment]
Hi @DaanKorver, what desktop environment are you using?
Also, does the command work when you run it from the terminal?

**Comment by DaanKorver** [comment]
I am using GNOME on Pop_OS!. Starting PS using the command on the terminal does work.

**Comment by YoungFellow-le** [comment]
Okay, I got the same problem on cinnamon.
Can you try changing the `photoshop.desktop` file's `Exec=...` command to:
```bash
./home/daan/Downloads/Linux-PhotoshopCC-v22/launcher.sh
```
I think this should fix it.

**Comment by DaanKorver** [comment]
Still doesn't show up for me :/

**Comment by YoungFellow-le** [comment]
After doing some reading, this should help. Add this line to the .desktop file:
```bash
NoDisplay=false
```

However, this problem can be of many reasons. So I'll make sure that we solve it so that I can edit the script so it works with all DEs

**Comment by MiMillieuh** [comment]
Try this in your exec : 
`bash -c 'cd "/home/daan/Downloads/Linux-PhotoshopCC-v22/PS-Prefix/drive_c/Program Files/Adobe/Adobe Photoshop 2021/" && WINEPREFIX="/home/daan/Downloads/Linux-PhotoshopCC-v22/PS-Prefix" wine photoshop.exe'`$

I haven't checked modification on that fork so it might not work. but you can't add more than 1 command in a desktop entry so bash -c should do the trick

**Comment by riquezjp** [comment]
Using Manjaro Gnome42, none of the suggestions work so far. 
Although the app icon does appear in apps using a single command in the .desktop as @[MiMillieuh](https://github.com/MiMillieuh) noted. But it doesn't launch PS.

```
5月 24 21:43:39 Sulaco systemd[1127]: Started Application launched by gnome-shell.
 5月 24 21:43:41 Sulaco photoshop.desktop[4534]: Application could not be started, or no application associated with the specified file.
 5月 24 21:43:41 Sulaco photoshop.desktop[4534]: ShellExecuteEx failed: File not found.
```
```
Exec=bash -c 'cd "/home/rico/Library/Linux-PhotoshopCC-v22/PS-Prefix/drive_c/Program Files/Adobe/Adobe Photoshop 2021/" && WINEPREFIX="/home/rico/Library/Linux-PhotoshopCC-v22/PS-Prefix" wine photoshop.exe'$
```
Running the 'cd &&'  in a terminal DOES launch PS, but the bash -c gives file not found.

**Comment by riquezjp** [comment]
ok, now got it working!
a combination of the two solutions!

`Exec=bash -c /home/rico/Library/Linux-PhotoshopCC-v22/launcher.sh`

**Comment by albakhtari** [comment]
Seems to be solved for most people, therefore I'll close the issue and implement the solution in the [new repo](https://github.com/YoungFellow-le/Ps-22-Linux).
