### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Fluffy-Bean** [YoungFellow-le/Linux-PhotoshopCC-v22#4]
When I run installer.sh, I get this error
```
./installer.sh: line 37: syntax error near unexpected token `fi'
./installer.sh: line 37: `fi'
```

**Comment by YoungFellow-le** [comment]
I cannot reproduce that error on my setup.
But I'm presuming that it's because it's not being executed as a bash script.
So please try to run it again like stated in the instructions:
```shell
bash installer.sh

############

bash uninstaller.sh
```

**Comment by flleeppyy** [comment]
Getting the same error.
On Pop!_OS 22.04 LTS x86_64
Bash: 5.1.16(1)-release (x86_64-pc-linux-gnu)
